services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: exemple_root
      MYSQL_DATABASE: exemple_db
      MYSQL_USER: exemple_user
      MYSQL_PASSWORD: exemple_pwd

  wordpress:
    image: wordpress:latest
    depends_on:
      - db  # le service WordPress attend que MySQL soit prêt
    ports:
      - "8000:80"  # permet d'accéder à WordPress via localhost:8000
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: exemple_db
      WORDPRESS_DB_USER: exemple_user
      WORDPRESS_DB_PASSWORD: exemple_pwd

volumes:
  db_data:  # volume pour stocker les données MySQL
